### PR TITLE
Modify data annotation code for lifting tasks

### PR DESCRIPTION
**Pull request by Zweisteine96**
This pr is related to this issue #73 .

### CODE REVIEW

**Comment by Zweisteine96** [comment]
Hi @kouroshD, @lrapetti , this PR consists of the following main changes:
- how to compile and run the repo
- adaption to the new type FT Shoe data
- using remapper device to read/open the data instead of creating a new port

**Comment by DanielePucci** [comment]
I agree that the master branch of this repo is a good location! Probably, we can commit the code in this branch, and once the paper will get accepted, we move the corresponding code - associated to the paper results - here https://github.com/ami-iit/paper_darvish_2022_ral_action-kindyn-predicition

@kouroshD do you agree?

**Comment by traversaro** [comment]
> I think what would be better is to define a location for the action and intention recognition code where different people can contribute. @kouroshD what do you think about that? The `master` branch of this repo might be a good location, or should we put it somewhere else?
> cc @traversaro @DanielePucci

I guess @kouroshD may have the most informated option, but a possible option is at some point to have a `human-action-intention-recognition` or similar standalone repo.

**Comment by kouroshD** [comment]
Hi,
My idea is as mentioned by @DanielePucci , as soon as the paper get accepted, we push that code version to https://github.com/ami-iit/paper_darvish_2022_ral_action-kindyn-predicition. But in this repo, the code can continue to be developed.

I believe the master branch is a good place to keep the clean version of the code. I'll try to work on the code on May and merge to master. 

> I guess @kouroshD may have the most informated option, but a possible option is at some point to have a human-action-intention-recognition or similar standalone repo.

What do you mean @traversaro ? Are you suggested having another repo for the code, or you mean this repo.


About this PR, in the current version it cannot be merged. The PR should get clean before putting it for review. The reasons are:
- There are learned model `.h5` files ( e.g., https://github.com/ami-iit/element_human-action-intention-recognition/pull/74/files#diff-3205277c27803d4f53b91f33e66e62597f91579a086c2425944a6f1ed21f7179) that I think they are not necessary to put them online. At least in the branch that is currently open against (https://github.com/ami-iit/element_human-action-intention-recognition/tree/ral_submission), neither master branch.
- There are models images (.png) again, I am not pro of merging them here.
- There are many `.txt` datasets files, that are not supposed to be merged here. Why? foremost, if for any application we want to merge the dataset to this repo, after some point, the repo becomes super heavy which makes it hard to pull and push. In this PR, there are many `.txt` files, in which some of them I believe even @Zweisteine96  are not using all of those.
- In general, we have to think of how to deal with datasets @traversaro . 
-  there are some `.csv` files, that honestly I do not know why they are in the PR.
- Some changes in the code, are application specific (ergonomics here), for example an NN architecture. I am not sure, if it is correct to merge them in this fork or branch. 
- Some changes in the code, should be avoided in theory when the code is cleaner, they will move to the config files.

My suggestion is for the time being, @Zweisteine96  can keep the changes relevant to his application domain, in **another fork**. Keeping them in this fork, make the repo heavy, and I would like to avoid using lfs for this repo. He may only open a new PR (or clean this one) with only, bug fixes and updates to the documentation. I think the rest of the PR is not mergeable.

**Comment by traversaro** [comment]
> What do you mean @traversaro ? Are you suggested having another repo for the code, or you mean this repo.

I meant that if you feel that it is convenient, we can have a different repo with just the code, the main benefit are:
* Clear separation of element (management, tipically specific of one person) and code (that is mantained by one person, but to which several persons can contribute)
* Clear documentation, as the README for the code repo just contains the instructions on how to document to install/use the code, no additional management related information.

We recent discussed with @S-Dafarra on this and indeed we agreed on this point. However, I think we did not reach the general consensus or even a clear idea on this, so if you think it is better to continue to have the code in the `element_***` repo, feel free to do so!

> In general, we have to think of how to deal with datasets @traversaro .

Good point. I think that currently the approaches in the lab are:
* Upload to the repo (not convenient for big datasets, as they make the repo difficult to clone)
* Upload the data to OneDrive
* Upload the data to a network drive (I guess iRonCub uses this strategy)

In general I think we do not have a lot of experience with this in the line, so any suggestion is welcome.

**Comment by lrapetti** [comment]
> > What do you mean @traversaro ? Are you suggested having another repo for the code, or you mean this repo.
> 
> I meant that if you feel that it is convenient, we can have a different repo with just the code, the main benefit are:
> 
> * Clear separation of element (management, tipically specific of one person) and code (that is mantained by one person, but to which several persons can contribute)
> * Clear documentation, as the README for the code repo just contains the instructions on how to document to install/use the code, no additional management related information.
> We recent discussed with @S-Dafarra on this and indeed we agreed on this point. However, I think we did not reach the general consensus or even a clear idea on this, so if you think it is better to continue to have the code in the element_*** repo, feel free to do so!



In the long run I also think this might be a good solution (maybe after cleaning the code).


Concerning now, @Zweisteine96 can keep working on a separate branch (why @kouroshD you mentioned a separate fork?) but we should keep in mind that some of the changes he introduced might be useful to be brought in the main branch, so if @kouroshD you are planning to work on the code to clean it you can align with his modifications.

**Comment by kouroshD** [comment]
> Concerning now, @Zweisteine96 can keep working on a separate branch (why @kouroshD you mentioned a separate fork?) but we should keep in mind that some of the changes he introduced might be useful to be brought in the main branch, so if @kouroshD you are planning to work on the code to clean it you can align with his modifications.

I mentioned another fork, since if I pull all the branches, this PR branch has datasets and models in it which I think they are not small (at least 200MB in total). 
About what can be merged, I already mentioned in https://github.com/ami-iit/element_human-action-intention-recognition/pull/74#issuecomment-1111890248 the parts of the modifications that I see are OK to merge. Maybe I missed some parts that can be helpful to merge,  @Zweisteine96 can add those as well to the PR.

**Comment by lrapetti** [comment]
@Zweisteine96 can you check if this PR should be still merged or we can close it?

**Comment by Zweisteine96** [comment]
Closing since the code modification already in this branch https://github.com/ami-iit/element_human-action-intention-recognition/tree/feature4NIOSH. We should decide I f we merge this branch with master.

**Pull request closed without merging**
